name: math_corn
description: "A new Flutter project."

publish_to:


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  equatable: ^2.0.7
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  hydrated_bloc: ^10.1.1
  animated_splash_screen: ^1.3.0
  chewie: ^1.12.1
  flutter_secure_storage: ^9.2.4
  sizer: ^3.0.5
  fluttertoast: ^8.2.12
  youtube_explode_dart: ^2.5.2
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  cloud_firestore: ^6.0.0
  connectivity_plus: ^6.1.5
  path_provider: ^2.1.5
  flutter_svg: ^2.2.0
  youtube_player_flutter: ^9.1.2
  flutter_pdfview: ^1.4.1+1
  syncfusion_flutter_pdfviewer: ^30.2.7
  package_info_plus: ^8.3.1
  flutter_paymob: ^1.0.8
  firebase_storage: ^13.0.0
  flutter_local_notifications: ^19.4.1
  file_picker: ^10.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:


  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/errors/



  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 900
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 600


flutter_intl:
  enabled: true
